In [1]:
import configparser

import pandas as pd

config = configparser.ConfigParser()
config.read('config.ini')

['config.ini']

In [2]:
df = pd.read_pickle(config['DEFAULT']['ProjectDirectory']+'/dataframe/assoc.pkl')

In [3]:
columns = ['freq'] + list(df.columns[-10:])

# _Interaction salience_ and _log Dice salience_ seem the best

In [4]:
df.sort_values('freq', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact,npmi,niact,pmi_sali,iact_sali,ldice,ldice_sali
nsubj,ROOT,dobj,,,,,,,,,,,
I,think,,124841593,26.895523,-6.671204,3.245796,0.346137,0.486538,0.051885,87.297370,9.309535,26.859788,722.408051
it,be,,98405827,26.552240,-7.014487,2.037887,0.614009,0.290525,0.087534,54.110460,16.303310,26.553518,705.055394
I,know,,59471252,25.825689,-7.741038,2.208507,0.268879,0.285298,0.034734,57.036202,6.943983,25.790741,666.063659
that,be,,57715894,25.782465,-7.784262,1.867656,0.361413,0.239927,0.046429,48.152784,9.318106,25.817769,665.645738
I,have,,50336742,25.585109,-7.981619,0.017357,0.106565,0.002175,0.013351,0.444074,2.726474,25.454472,651.255431

In [5]:
df.sort_values('pmi', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact,npmi,niact,pmi_sali,iact_sali,ldice,ldice_sali
nsubj,ROOT,dobj,,,,,,,,,,,
wwq.thai,vww.call,B.xxx,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
Canda,capai,varuvaye,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
Ruttkamp,8r,18.990,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
acqua,appiccicose,scivolose,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
agit,célestes,géométrie,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0

In [7]:
df.sort_values('iact', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact,npmi,niact,pmi_sali,iact_sali,ldice,ldice_sali
nsubj,ROOT,dobj,,,,,,,,,,,
mehroh,corhi,liardun,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
moma,arabo,vkdeolarä±.com,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
ing_xvmc,using_xvmc_vld,using_bindings_perl,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
ApJServGroup,set1,jserv1.properties,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
Otoccpn,ateanntit,zeoyvenawoy,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0

In [8]:
df.sort_values('pmi_sali', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact,npmi,niact,pmi_sali,iact_sali,ldice,ldice_sali
nsubj,ROOT,dobj,,,,,,,,,,,
ED02,93e,8dba,85462,16.382995,-17.183732,34.367464,17.183732,2.000000,1.000000,563.042002,281.521001,31.315484,513.041429
imágenes,utilizar,comerciale,60185,15.877116,-17.689611,35.379222,17.689611,2.000000,1.000000,561.720023,280.860011,31.315484,497.199580
Nous,somme,survenue,53824,15.715962,-17.850765,35.451336,17.721152,1.985984,0.992739,557.151849,278.504955,31.230891,490.823501
se,encuentra,imagen,60185,15.877116,-17.689611,35.023202,17.341908,1.979874,0.980344,556.067446,275.339499,31.190591,495.216642
Sie,diese,Fenster,48993,15.580288,-17.986439,35.639338,17.695149,1.981456,0.983805,555.271155,275.695518,31.202185,486.139030

In [9]:
df.sort_values('iact_sali', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact,npmi,niact,pmi_sali,iact_sali,ldice,ldice_sali
nsubj,ROOT,dobj,,,,,,,,,,,
ED02,93e,8dba,85462,16.382995,-17.183732,34.367464,17.183732,2.000000,1.000000,563.042002,281.521001,31.315484,513.041429
imágenes,utilizar,comerciale,60185,15.877116,-17.689611,35.379222,17.689611,2.000000,1.000000,561.720023,280.860011,31.315484,497.199580
Nous,somme,survenue,53824,15.715962,-17.850765,35.451336,17.721152,1.985984,0.992739,557.151849,278.504955,31.230891,490.823501
Sie,diese,Fenster,48993,15.580288,-17.986439,35.639338,17.695149,1.981456,0.983805,555.271155,275.695518,31.202185,486.139030
se,encuentra,imagen,60185,15.877116,-17.689611,35.023202,17.341908,1.979874,0.980344,556.067446,275.339499,31.190591,495.216642

In [10]:
df.sort_values('npmi', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact,npmi,niact,pmi_sali,iact_sali,ldice,ldice_sali
nsubj,ROOT,dobj,,,,,,,,,,,
estaban,hinchada,contraida,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.000000,0.000000,31.315484,0.000000
expéditions,d'amundsen,retrouvées,2,1.0,-32.566727,65.133455,32.566727,2.0,1.0,65.133455,32.566727,31.315484,31.315484
reste,interdit,reste,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.000000,0.000000,31.315484,0.000000
Wojueai,nse,KATIiAIItON,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.000000,0.000000,31.315484,0.000000
AR114,9c48e65b6d340f5af24013776fc04e03,00058,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.000000,0.000000,31.315484,0.000000

In [11]:
df.sort_values('niact', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact,npmi,niact,pmi_sali,iact_sali,ldice,ldice_sali
nsubj,ROOT,dobj,,,,,,,,,,,
imágenes,utilizar,comerciale,60185,15.877116,-17.689611,35.379222,17.689611,2.0,1.0,561.720023,280.860011,31.315484,497.199580
ED02,93e,8dba,85462,16.382995,-17.183732,34.367464,17.183732,2.0,1.0,563.042002,281.521001,31.315484,513.041429
It_Staff_TitanScepter,it_staff_twobladed,It_Staff_WarSpear,3,1.584963,-31.981765,63.963530,31.981765,2.0,1.0,101.379796,50.689898,31.315484,49.633868
using_firewire,using_iptv,using_ivtv,7,2.807355,-30.759372,61.518745,30.759372,2.0,1.0,172.704951,86.352475,31.315484,87.913678
Shànghǎi,dàxué,Nǎiróng,7,2.807355,-30.759372,61.518745,30.759372,2.0,1.0,172.704951,86.352475,31.315484,87.913678

In [13]:
df.sort_values('ldice', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact,npmi,niact,pmi_sali,iact_sali,ldice,ldice_sali
nsubj,ROOT,dobj,,,,,,,,,,,
Mamman,ddefki,nmel,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
torbasus,tasarlamak,süslemek,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
JAP,recid,etock,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
JFUSgEIilL,dgent,memphi,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0
entie,peuptung,homhie,1,0.0,-33.566727,67.133455,33.566727,2.0,1.0,0.0,0.0,31.315484,0.0

In [14]:
df.sort_values('ldice_sali', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact,npmi,niact,pmi_sali,iact_sali,ldice,ldice_sali
nsubj,ROOT,dobj,,,,,,,,,,,
I,think,,124841593,26.895523,-6.671204,3.245796,0.346137,0.486538,0.051885,87.297370,9.309535,26.859788,722.408051
it,be,,98405827,26.552240,-7.014487,2.037887,0.614009,0.290525,0.087534,54.110460,16.303310,26.553518,705.055394
I,know,,59471252,25.825689,-7.741038,2.208507,0.268879,0.285298,0.034734,57.036202,6.943983,25.790741,666.063659
that,be,,57715894,25.782465,-7.784262,1.867656,0.361413,0.239927,0.046429,48.152784,9.318106,25.817769,665.645738
I,have,,50336742,25.585109,-7.981619,0.017357,0.106565,0.002175,0.013351,0.444074,2.726474,25.454472,651.255431