In [1]:
import pandas as pd

In [14]:
df = pd.read_pickle('/mnt/permanent/home/makrai/project/verb-tensor/top_level/dataframe/assoc00.pkl')

In [3]:
columns = ['freq']+list(df.columns[-7:])

In [4]:
df[columns].describe(percentiles=[])

,freq,log_freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice
count,1.021745e+06,1.021745e+06,1.021745e+06,1.021745e+06,1.021745e+06,1.021745e+06,1.021745e+06,1.021745e+06
mean,1.567937e+00,2.172035e-01,-2.039427e+01,1.350790e+01,4.102719e+01,2.223820e+00,7.920227e+00,-2.933315e+01
std,1.181224e+01,6.546951e-01,6.546951e-01,7.542278e+00,4.596785e+00,8.057600e+00,2.251718e+01,3.163395e+00
min,1.000000e+00,0.000000e+00,-2.061147e+01,0.000000e+00,1.020526e+01,0.000000e+00,0.000000e+00,-3.446847e+01
50%,1.000000e+00,0.000000e+00,-2.061147e+01,1.258225e+01,4.171286e+01,0.000000e+00,0.000000e+00,-2.947030e+01
max,5.436000e+03,1.240833e+01,-8.203142e+00,4.122294e+01,5.662716e+01,2.059408e+02,2.193936e+02,-1.723424e+01

# Interaction information seems the best

In [5]:
df.head()[columns]

,,,freq,log_freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice
nsubj,ROOT,dobj,,,,,,,,
we,support,browser,5436,12.408330,-8.203142,11.088061,13.436515,137.584314,166.724707,-19.991665
Package,have,suggest,3854,11.912141,-8.699331,11.055383,14.960397,131.693278,178.210351,-21.919878
we,reserve,right,3397,11.730046,-8.881426,11.126692,14.895979,130.516598,174.730511,-20.607370
I,have,idea,2561,11.322492,-9.288980,4.278333,18.117759,48.441393,205.138174,-23.152059
coating,protect,print,2434,11.249113,-9.362358,17.880035,10.205262,201.134543,114.800151,-17.532822

In [6]:
df.sort_values('pmi', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice
nsubj,ROOT,dobj,,,,,,,,
Viver,leva,Desordem,1,0.0,-20.611472,41.222943,20.611472,0.0,0.0,-17.234237
Tren,rambut,berponus,1,0.0,-20.611472,41.222943,20.611472,0.0,0.0,-17.234237
vieory,mwa,emy,1,0.0,-20.611472,41.222943,20.611472,0.0,0.0,-17.234237
Medicīnas,nozare,konference,1,0.0,-20.611472,41.222943,20.611472,0.0,0.0,-17.234237
Obnubile,etait,dernier,1,0.0,-20.611472,41.222943,20.611472,0.0,0.0,-17.234237

In [7]:
df.sort_values('iact_info', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice
nsubj,ROOT,dobj,,,,,,,,
everyone,offer,6,1,0.0,-20.611472,4.207258,56.627156,0.0,0.0,-30.900831
court,play,right,1,0.0,-20.611472,6.092327,55.742087,0.0,0.0,-29.486213
paper,read,$,1,0.0,-20.611472,6.239619,55.594796,0.0,0.0,-28.983967
FIG.,b.,activity,1,0.0,-20.611472,6.240446,55.593969,0.0,0.0,-29.347003
place,contain,you,1,0.0,-20.611472,5.417458,55.416956,0.0,0.0,-30.484240

In [8]:
df.sort_values('salience', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice
nsubj,ROOT,dobj,,,,,,,,
Donec,id,turpis,472,8.882643,-11.728828,23.184635,12.001851,205.940836,106.608154,-17.329828
WebMD,disclaim,warranty,1076,10.071462,-10.540009,20.006375,11.566173,201.493458,116.488279,-17.608135
coating,protect,print,2434,11.249113,-9.362358,17.880035,10.205262,201.134543,114.800151,-17.532822
NYSE,delay,minute,1031,10.009829,-10.601643,20.049954,11.750783,200.696600,117.623327,-17.702841
incase,please,contact,839,9.712527,-10.898945,20.289979,12.289659,197.066965,119.363647,-17.777919

In [9]:
df.sort_values('iact_sali', ascending=False).head()[columns]

                     freq   log_freq   log_prob       pmi  iact_info  \
nsubj ROOT dobj
we    have time       733   9.517669 -11.093802  2.724775  23.051193
I     have question  1254  10.292322 -10.319150  3.884581  21.182457
we    be   who        292   8.189825 -12.421647  9.588979  26.368228
      have part       337   8.396605 -12.214867  3.309202  25.620308
this  have nothing    193   7.592457 -13.019014  3.965747  28.328873

                      salience   iact_sali   log_dice
nsubj ROOT dobj
we    have time      25.933506  219.393631 -24.713685
I     have question  39.981356  218.016665 -24.174493
we    be   who       78.532053  215.951160 -24.232319
      have part      27.786065  215.123603 -25.807330
this  have nothing   30.109764  215.085755 -26.330149

In [10]:
df.sort_values('log_dice', ascending=False).head()[columns]

,,,freq,log_freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice
nsubj,ROOT,dobj,,,,,,,,
Games/Avg,6/0,5/939,1,0.0,-20.611472,41.222943,20.611472,0.0,0.0,-17.234237
sensore,rassegnarsi,pulizium,1,0.0,-20.611472,41.222943,20.611472,0.0,0.0,-17.234237
Frénicle,triangle,demontrées,1,0.0,-20.611472,41.222943,20.611472,0.0,0.0,-17.234237
Fréamh,féach,Gaoithe,1,0.0,-20.611472,41.222943,20.611472,0.0,0.0,-17.234237
Polecamy,książkę,Wąsia,1,0.0,-20.611472,41.222943,20.611472,0.0,0.0,-17.234237