In [1]:
import pickle as pkl

In [2]:
df = pkl.load(open('/mnt/permanent/home/makrai/project/verb-tensor/top_level/dataframe/assoc0000.pkl', mode='rb'))

In [3]:
df.describe(percentiles=[])[['freq']+list(df.columns[10:])]

,freq,log_freq,log_dice,pmi,iact_info,salience,iact_sali
count,21099.000000,21099.000000,21099.000000,21099.000000,21099.000000,21099.000000,21099.000000
mean,1.175506,-14.505894,-6.986015,14.966580,26.078360,-217.343867,-378.623692
std,2.281821,0.411271,2.601182,5.439371,3.862756,79.684435,58.444325
min,1.000000,-14.598169,-10.814048,0.000000,7.098565,-426.213067,-543.982075
50%,1.000000,-14.598169,-7.357552,14.539243,26.350549,-211.695995,-383.557344
max,258.000000,-6.586942,0.000000,29.196338,37.263720,-0.000000,-46.757831

# Interaction information seems the best

In [4]:
df.head()

,nsubj,ROOT,dobj,freq,freq_nsubj,freq_ROOT,freq_dobj,"freq_('nsubj', 'ROOT')","freq_('nsubj', 'dobj')","freq_('ROOT', 'dobj')",log_freq,log_dice,pmi,iact_info,salience,iact_sali
38,Copyright,©,al,258,-6.126494,-6.086416,-6.570263,-6.126494,-6.586942,-6.581361,-6.586942,-0.341920,12.196231,7.098565,-80.335862,-46.757831
2023,dtoider,have,party,78,-8.312767,-2.852495,-8.122435,-8.312767,-8.312767,-8.276241,-8.312767,-3.943817,10.974930,13.926844,-91.232031,-115.770605
847,I,love,it,59,-3.727034,-6.317398,-6.810266,-6.685280,-7.803753,-8.620889,-8.715526,-3.764216,8.139172,14.970749,-70.937165,-130.477951
782,Gutenberg,ebook,-lrb-,58,-8.715526,-8.715526,-7.586942,-8.715526,-8.740188,-8.740188,-8.740188,-0.505424,16.277805,9.918096,-142.271076,-86.686024
9411,repair,fail,query,53,-8.870248,-8.816809,-8.790814,-8.870248,-8.870248,-8.870248,-8.870248,-0.044669,17.607623,9.003122,-156.183990,-79.859929

In [5]:
df.sort_values('pmi', ascending=False).head()

,nsubj,ROOT,dobj,freq,freq_nsubj,freq_ROOT,freq_dobj,"freq_('nsubj', 'ROOT')","freq_('nsubj', 'dobj')","freq_('ROOT', 'dobj')",log_freq,log_dice,pmi,iact_info,salience,iact_sali
5876,Spongiae,littorale,Caspii,1,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,0.0,29.196338,14.598169,-426.213067,-213.106534
2061,Acteocina,smirna,Dall,1,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,0.0,29.196338,14.598169,-426.213067,-213.106534
9680,Bloggaan,ettei,unohdu,1,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,0.0,29.196338,14.598169,-426.213067,-213.106534
20251,AVG,immitate,ie6,1,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,0.0,29.196338,14.598169,-426.213067,-213.106534
20194,Esta,ensalada,adelantado,1,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,0.0,29.196338,14.598169,-426.213067,-213.106534

In [6]:
df.sort_values('iact_info', ascending=False).head()

,nsubj,ROOT,dobj,freq,freq_nsubj,freq_ROOT,freq_dobj,"freq_('nsubj', 'ROOT')","freq_('nsubj', 'dobj')","freq_('ROOT', 'dobj')",log_freq,log_dice,pmi,iact_info,salience,iact_sali
9798,I,include,diagram,1,-3.727034,-4.218790,-11.598169,-13.013206,-14.598169,-14.598169,-14.598169,-10.064743,4.945824,37.263720,-72.199976,-543.982075
431,I,show,thrill,1,-3.727034,-4.588340,-13.013206,-14.598169,-14.598169,-14.598169,-14.598169,-9.920353,6.730411,37.064095,-98.251682,-541.067919
3264,what,have,this,1,-8.870248,-2.852495,-8.870248,-14.598169,-13.598169,-14.598169,-14.598169,-10.204571,5.994822,36.799684,-87.513430,-537.208001
5421,these,have,process,1,-8.428244,-2.852495,-9.350241,-14.598169,-14.598169,-13.598169,-14.598169,-10.206200,6.032811,36.761696,-88.067991,-536.653440
14192,I,require,product,1,-3.727034,-7.051274,-11.013206,-14.598169,-14.598169,-14.598169,-14.598169,-9.431846,7.193346,36.601161,-105.009673,-534.309928

In [7]:
df.sort_values('salience', ascending=False).head()

,nsubj,ROOT,dobj,freq,freq_nsubj,freq_ROOT,freq_dobj,"freq_('nsubj', 'ROOT')","freq_('nsubj', 'dobj')","freq_('ROOT', 'dobj')",log_freq,log_dice,pmi,iact_info,salience,iact_sali
11938,we,have,role,1,-4.249441,-2.852495,-7.350241,-6.998256,-13.013206,-9.553775,-14.598169,-10.670656,0.000000,29.711229,-0.000000,-433.729543
10005,I,have,number,1,-3.727034,-2.852495,-8.043580,-5.866850,-14.598169,-9.954313,-14.598169,-10.814048,0.024939,30.394392,-0.364068,-443.702466
9555,we,have,time,1,-4.249441,-2.852495,-7.609484,-6.998256,-11.790814,-9.954313,-14.598169,-10.663262,0.113251,28.630132,-1.653250,-417.947502
16224,I,have,evidence,1,-3.727034,-2.852495,-8.276241,-5.866850,-14.598169,-13.013206,-14.598169,-10.810304,0.257600,33.220625,-3.760489,-484.960292
15645,we,have,result,1,-4.249441,-2.852495,-7.765279,-6.998256,-10.790814,-13.013206,-14.598169,-10.659401,0.269045,30.533231,-3.927567,-445.729262

In [8]:
df.sort_values('iact_sali', ascending=False).head()

,nsubj,ROOT,dobj,freq,freq_nsubj,freq_ROOT,freq_dobj,"freq_('nsubj', 'ROOT')","freq_('nsubj', 'dobj')","freq_('ROOT', 'dobj')",log_freq,log_dice,pmi,iact_info,salience,iact_sali
38,Copyright,©,al,258,-6.126494,-6.086416,-6.570263,-6.126494,-6.586942,-6.581361,-6.586942,-0.341920,12.196231,7.098565,-80.335862,-46.757831
9411,repair,fail,query,53,-8.870248,-8.816809,-8.790814,-8.870248,-8.870248,-8.870248,-8.870248,-0.044669,17.607623,9.003122,-156.183990,-79.859929
782,Gutenberg,ebook,-lrb-,58,-8.715526,-8.715526,-7.586942,-8.715526,-8.740188,-8.740188,-8.740188,-0.505424,16.277805,9.918096,-142.271076,-86.686024
124,author,declare,conflict,52,-7.340781,-8.643973,-8.489644,-8.790814,-8.598169,-8.897729,-8.897729,-0.864345,15.576669,10.710043,-138.596980,-95.295062
1669,residency,explore,intersection,38,-9.350241,-8.331382,-9.350241,-9.350241,-9.350241,-9.350241,-9.350241,-0.424498,17.681624,10.369100,-165.327448,-96.953591

In [9]:
df.sort_values('log_dice', ascending=False).head()

,nsubj,ROOT,dobj,freq,freq_nsubj,freq_ROOT,freq_dobj,"freq_('nsubj', 'ROOT')","freq_('nsubj', 'dobj')","freq_('ROOT', 'dobj')",log_freq,log_dice,pmi,iact_info,salience,iact_sali
4338,Ecology,unintend,Engagement,1,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,0.0,29.196338,14.598169,-426.213067,-213.106534
9600,Los,sim,accesorio,1,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,0.0,29.196338,14.598169,-426.213067,-213.106534
1911,Coryne,vanbenedeni,Hincks,1,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,0.0,29.196338,14.598169,-426.213067,-213.106534
4964,menghia,roti,tawar,1,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,0.0,29.196338,14.598169,-426.213067,-213.106534
19040,Vintage,rebuke,chairman,1,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,-14.598169,0.0,29.196338,14.598169,-426.213067,-213.106534