In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle('/mnt/permanent/home/makrai/project/verb-tensor/verb/dataframe/assoc0.pkl')

In [3]:
columns = ['freq'] + list(df.columns[-7:])

In [4]:
df[columns].describe(percentiles=[])

,freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice,dice_sali
count,1.217660e+07,1.217660e+07,1.217660e+07,1.217660e+07,1.217660e+07,1.217660e+07,1.217660e+07,1.217660e+07
mean,1.252094e+01,-2.590134e+01,1.037741e+01,5.459112e+01,9.347311e+00,6.201584e+01,6.873019e+00,1.019258e+01
std,2.749432e+02,1.762243e+00,7.849399e+00,6.246136e+00,1.747301e+01,7.874871e+01,3.182362e+00,1.720000e+01
min,1.000000e+00,-2.718388e+01,0.000000e+00,1.299906e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,1.000000e+00,-2.718388e+01,9.018444e+00,5.501304e+01,0.000000e+00,0.000000e+00,6.914537e+00,0.000000e+00
max,2.273200e+05,-9.389514e+00,5.436776e+01,8.019581e+01,3.654916e+02,4.323497e+02,2.415133e+01,3.733656e+02

# _Interaction salience_ and _log Dice salience_ seem the best

In [6]:
df[columns].head()

                      freq  log_prob       pmi  iact_info    salience  \
nsubj ROOT dobj
i     have problem  227320 -9.389514  3.181733  19.051029   56.616919
      tell you      209625 -9.506428  4.615581  19.725275   81.591711
      have idea     199283 -9.579420  3.265573  19.218080   57.488651
it    make sense    181600 -9.713474  8.315593  18.698598  145.276771
i     love it       159043 -9.904822  3.235146  18.685303   55.900282

                     iact_sali   log_dice   dice_sali
nsubj ROOT dobj
i     have problem  339.000973  17.774401  316.284189
      tell you      348.692586  18.198767  321.707814
      have idea     338.323896  17.587948  309.626306
it    make sense    326.672072  19.745722  344.965748
i     love it       322.864417  17.703923  305.907106

In [7]:
df.sort_values('pmi', ascending=False).head()[columns]

,,,freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice,dice_sali
nsubj,ROOT,dobj,,,,,,,,
co­hen,pho­to­graph,brace­let,1,-27.183879,54.367758,27.183879,0.0,0.0,24.151332,0.0
förväntningar,således,infriat,1,-27.183879,54.367758,27.183879,0.0,0.0,24.151332,0.0
chero,kee.k12.ga.us,schools/ccca/default,1,-27.183879,54.367758,27.183879,0.0,0.0,24.151332,0.0
castjnge,forsaid,roylbfe,1,-27.183879,54.367758,27.183879,0.0,0.0,24.151332,0.0
qntwhtospeyplp,gahncgqa,werafykzxu,1,-27.183879,54.367758,27.183879,0.0,0.0,24.151332,0.0

In [8]:
df.sort_values('iact_info', ascending=False).head()[columns]

,,,freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice,dice_sali
nsubj,ROOT,dobj,,,,,,,,
fig.,do,significance,1,-27.183879,0.355827,80.195810,0.0,0.0,3.941427,0.0
feature,think,obligation,1,-27.183879,2.833543,78.718094,0.0,0.0,6.176014,0.0
institution,contain,she,1,-27.183879,0.602961,77.626749,0.0,0.0,5.127459,0.0
apartment,know,storage,1,-27.183879,4.345226,77.206412,0.0,0.0,5.195947,0.0
use,©,forum,1,-27.183879,3.510308,77.041329,0.0,0.0,7.040200,0.0

In [9]:
df.sort_values('salience', ascending=False).head()[columns]

,,,freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice,dice_sali
nsubj,ROOT,dobj,,,,,,,,
declara,aceptar,images,6124,-14.603621,29.052790,14.758072,365.491612,185.660357,24.097990,303.158949
nous,somme,survenue,5336,-14.802336,29.445360,14.894559,364.578994,184.417617,24.097726,298.367031
donec,id,turpis,12186,-13.610942,26.790259,14.034657,363.622493,190.491521,23.995605,325.690835
sie,diese,fenster,4824,-14.947865,29.491776,15.313739,360.861786,187.379124,24.013666,293.831556
mashable,redefine,storytelling,8759,-14.087329,27.422803,14.839183,359.144124,194.342110,23.887493,312.843758

In [10]:
df.sort_values('iact_sali', ascending=False).head()[columns]

                          freq   log_prob       pmi  iact_info    salience  \
nsubj  ROOT     dobj
report see      day       4710 -14.982368  8.818224  35.434109  107.595666
you    reserve  price     3451 -15.431080  6.034110  36.379306   70.917675
       provide  we       10870 -13.775815  2.656313  31.791825   35.616020
people describe you       4119 -15.175801  7.163051  35.436806   86.014478
you    include  version   3736 -15.316600  2.556605  35.681075   30.339944

                          iact_sali   log_dice   dice_sali
nsubj  ROOT     dobj
report see      day      432.349680  16.134910  196.870285
you    reserve  price    427.558665  13.417128  157.688802
       provide  we       426.266834  14.840891  198.987616
people describe you      425.527944  16.020535  192.375835
you    include  version  423.437261  13.288371  157.696807

In [11]:
df.sort_values('log_dice', ascending=False).head()[columns]

,,,freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice,dice_sali
nsubj,ROOT,dobj,,,,,,,,
cuarnur,vontel,birlus,1,-27.183879,54.367758,27.183879,0.0,0.0,24.151332,0.0
idz,qalallahu,mutawaffika,1,-27.183879,54.367758,27.183879,0.0,0.0,24.151332,0.0
woodjame,walter1876,1953131,1,-27.183879,54.367758,27.183879,0.0,0.0,24.151332,0.0
qwfrrfwb,quue,fwcbgmibcd,1,-27.183879,54.367758,27.183879,0.0,0.0,24.151332,0.0
yetding,haten,ilsir,1,-27.183879,54.367758,27.183879,0.0,0.0,24.151332,0.0

In [12]:
df.sort_values('dice_sali', ascending=False).head()[columns]

,,,freq,log_prob,pmi,iact_info,salience,iact_sali,log_dice,dice_sali
nsubj,ROOT,dobj,,,,,,,,
use,constitute,acceptance,76240,-10.965619,18.788082,13.749909,304.710010,222.999604,23.021309,373.365580
coating,protect,print,61365,-11.278751,20.538427,13.292732,326.666322,211.422608,23.391421,372.043557
account,pend,confirmation,38739,-11.942380,22.828004,12.999062,347.932995,198.125194,23.781932,362.472290
inclusion,imply,recommendation,33146,-12.167332,21.614139,14.836271,324.569740,222.789569,23.158991,347.768088
jump,select,forum,44107,-11.755159,19.456473,15.734951,300.188478,242.770158,22.511379,347.321766